spring:
    application:
        name: UniversityCms

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5433/university_db
        username: admin
        password: 1111


    flyway:
        locations: db/migration
        baselineOnMigrate: true
        baselineVersion: 1
        baselineDescription: Base migration
        schemas:
            - public
            - university

    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    batch_size: 10
                order_updates: true
                order_inserts: true
    mvc:
        hiddenmethod:
            filter:
                enabled: true

university-cms:
    service:
        data-generator:
            url: http://localhost:8085

