name: u-cms

services:
    #app:
    #  build: ./UniversityCms
    #  ports:
    #    - "8080:8080"
    #  depends_on:
    #    - db_pg
    
    api_generator:
        image: api-generator
        build:
            context: ./UniversityGenerator
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8085:8081"
        depends_on:
            - db_pg_generator
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db_pg_generator:5432/university_db_gen
            - SPRING_PROFILES_ACTIVE=dev
        container_name: "api-generator"
    
    db_pg:
        image: postgres:16-alpine
        restart: always
        environment:
            POSTGRES_DB: university_db
            POSTGRES_USER: adminer
            POSTGRES_PASSWORD: 1111
        ports:
            - "5433:5432"
        container_name: "db-pg"
    
    db_pg_generator:
        image: postgres:16-alpine
        restart: always
        environment:
            POSTGRES_DB: university_db_gen
            POSTGRES_USER: adminer
            POSTGRES_PASSWORD: 1111
        ports:
            - "5434:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -q -d university_db_gen -U adminer" ]
            interval: 10s
            timeout: 20s
            retries: 5
        container_name: "db-pg-generator"

    adminer:
        image: adminer
        restart: always
        ports:
            - 8090:8080
        container_name: "adminer"

#network