spring:
    application:
        name: UniversityCms

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5433/university_db
        username: adminer
        password: 1111


    flyway:
        url: jdbc:postgresql://localhost:5433/university_db
        user: adminer
        password: 1111
        locations: db/migration
        baselineOnMigrate: true
        baselineVersion: 1
        baselineDescription: Base migration

    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    batch_size: 10
                order_updates: true
                order_inserts: true
    mvc:
        hiddenmethod:
            filter:
                enabled: true


