data:
    person:
        amount: 10

    group:
        amount: 10
        quantity_characters: 2
        quantity_numbers: 2
        char_first: 'A'
        char_last: 'Z'

    course:
        amount: 10

file-paths:
    first-names: /app/data/first_names.txt
    last-names: /app/data/last_names.txt