spring:
    application:
        name: "UniversityGenerator"

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5434/university_db_gen
        username: adminer
        password: 1111

    flyway:
        locations: db/migration
        baselineOnMigrate: true
        schemas:
            - public
            - university

    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    batch_size: 10
                order_updates: true
                order_inserts: true
server:
    port: 8081


# Parameters for generation
data:
    person:
        amount: 10

    group:
        amount: 10
        quantity_characters: 2
        quantity_numbers: 2
        char_first: 'A'
        char_last: 'Z'

    course:
        amount: 10


file-paths:
    first-names: src/main/resources/data/first_names.txt
    last-names: src/main/resources/data/last_names.txt